config/routes.rb
Kittybase::Application.routes.draw do
  get "pictures/show"

  get "pictures/destroy"

  get "pictures/new"

  get "sessions/new"

  get "users/new"

  get "pages/home"

  #get "kitties/:id/carouselitems"

  resources :users
  resources :kitties do
    member do
      get 'carouselitems'
    end
  end
  resources :pictures do
   member do
     get 'make_profile_pic'
   end
  end

  resources :sessions, :only => [:new, :create, :destroy]


  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/about', :to => 'pages#about'


root :to => 'pages#home'
end

app/models/kitty.rb
class Kitty < ActiveRecord::Base
  attr_accessible :name, :dob, :breed, :likes, :user_id
  belongs_to :user
  has_many :pictures
  
  validates :name, :presence => true,
            :length   => { :maximum => 50 }
  validates :user_id, :presence => true

end

app/models/picture.rb
class Picture < ActiveRecord::Base
belongs_to :kitty
has_attached_file :avatar,
                   :styles => { :medium => "300x300>",
                                :thumb => "100x100>" }

scope :profile_pic, where(:is_profile_pic => true)

def previous_pic
  self.class.first(:conditions => ["id < ? and kitty_id = ?", id, kitty_id], :order => "id desc")
end

def next_pic
  self.class.first(:conditions => ["id > ? and kitty_id = ?", id, kitty_id], :order => "id asc")
end


end

app/models/user.rb
# == Schema Information
# Schema version: 20110525222218
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#
require 'digest'

class User < ActiveRecord::Base
  has_many :kitties
  
  attr_accessible :name, :email, :password, :password_confirmation
  
  attr_accessor :password
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, :presence => true,
            :length   => { :maximum => 50 }
  validates :email, :presence => true,
            :format   => { :with => email_regex },
	    :uniqueness => { :case_sensitive => false }
  # Automatically create the virtual attribute 'password_confirmation'.
  validates :password, :presence => true,
      :confirmation => true,
      :length => { :within => 6..40 }
  
  before_save :encrypt_password
  
  
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  private
  
  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(password)
  end
  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end
  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end
  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
                  
                  
end
                  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/kitties_controller.rb
class KittiesController < ApplicationController
  
  def new
    @user = current_user
    @kitty = Kitty.new
    @title = "Add a new kitty!"
  end
  
  def create
    @user = current_user
    @kitty = Kitty.new(params[:kitty])
    if @kitty.save      
      flash[:success] = "Kitty created successfully!"
      
      redirect_to @kitty
    else
      flash[:failure] = "Kitty not created!"
      render 'new'
      
    end
  end
  
  def show
    @kitty = Kitty.find(params[:id])
    @pictures = @kitty.pictures
  end
  
  def carouselitems
    @kitty = Kitty.find(params[:id])
    @pictures = @kitty.pictures
    render 'carouselitems', :layout => false 
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
    def home
   @title = "Home"
  end
  
  def about
    @title = "About"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def show
    @picture = Picture.find(params[:id])
  end

  def destroy
  end

  def new
    @picture = Picture.new
    @kitty = Kitty.find(params[:kitty_id])
  end

  def make_profile_pic
    @picture = Picture.find(params[:id])
    @picture.kitty.pictures.each do |reset|
      # Set all to false first
      reset.is_profile_pic = false
      reset.save
    end
    # Set the active one to true
    @picture.is_profile_pic = true
    @picture.save
    redirect_to @picture
  end
  
  def create
    @kitty = Kitty.find(params[:picture][:kitty_id])
    @picture = Picture.new( params[:picture] )
    if @picture.save
      flash[:success] = "Picture successfully uploaded!"
      if (@kitty.pictures.size == 1)
	@picture.is_profile_pic = true
	@picture.save
      end
    
    redirect_to @kitty
    else
      flash[:failure] = "Something went wrong during the upload."
      render 'new'
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end
  
  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_back_or user
    end
    
    
  end
def destroy
sign_out
redirect_to root_path
end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user, :only => :destroy

  
  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name
    @kitties = @user.kitties
  end
  
  def new
    @user = User.new
    @title = "Sign up"
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      
      flash[:success] = "Welcome to KittyBase!  Your account has been created successfully.  Now add a kitty!"
      
      redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
    @title = "Edit user"
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end
  
 def destroy
User.find(params[:id]).destroy
flash[:success] = "User destroyed."
redirect_to users_path
end
 
  private
  def authenticate
    deny_access unless signed_in?
  end
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def logo
    image_tag("kittybase_logo.gif", :alt => "KittyBase Logo", :class => "round")
  end

end

app/helpers/kitties_helper.rb
module KittiesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def signed_in?
    !current_user.nil?
  end
  def current_user?(user)
    user == current_user
  end
  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end
  
    def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end
  
  private
  def user_from_remember_token
    User.authenticate_with_salt(*remember_token)
  end
  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end
  
  def store_location
    session[:return_to] = request.fullpath
  end
  def clear_return_to
    session[:return_to] = nil
  end
  
  
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user, options = { :size => 50 })
gravatar_image_tag(user.email.downcase, :alt => user.name,
:class => 'gravatar',
:gravatar => options)
end

end

app/views/kitties/_kitty.html.erb
<td class="kitty">
<% if kitty.pictures.any? %>
  <%= image_tag(kitty.pictures.profile_pic[0].avatar.url(:thumb)) %>
<% else %>
  <%= image_tag('/images/no_kitty.gif') %>
<% end %><BR>
<B><%= link_to kitty.name, kitty_path(:id => kitty.id) %></B>

</td>

app/views/kitties/carouselitems.html.erb
<%= render @pictures %>

app/views/kitties/new.html.erb
<h1>Add a new kitty!</h1>
<%= form_for(@kitty) do |f| %>
<%= render 'shared/error_messages', :object => f.object %>

<div class="field">
<%= f.label :name %><br />
<%= f.text_field :name %>
</div>
<div class="field">
<%= f.label :dob %><br />
<!--<%= f.text_field :dob %>-->
<%= f.date_select :dob, :start_year => 1980 %>
</div>
<div class="field">
<%= f.label :breed %><br />
<%= f.text_field :breed %>
</div>
<div class="field">
<%= f.label :likes %><br />
<%= f.text_field :likes %>
</div>
<%= f.hidden_field :user_id, { :value => @user.id } %>
<div class="actions">
<%= f.submit "Add kitty!" %>
</div>
<% end %>

</div>

app/views/kitties/show.html.erb
  <%= javascript_include_tag 'jcarousel/lib/jquery.jcarousel.min','carousel_init' %>

    <%= stylesheet_link_tag 'skins/tango/skin.css', :media => 'screen' %>

<font class=featured><%= @kitty.name %></font>
&nbsp;&nbsp;(belongs to <%= link_to @kitty.user.name, user_path(:id => @kitty.user.id) %>)
<TABLE><TR><TD>
Age: <%= distance_of_time_in_words(@kitty.dob,Time.now) %>
</TD><TD>
Breed: <%= @kitty.breed %>
</TD><TD>
Likes: <%= @kitty.likes %>
</TD>
</TR></TABLE>
<BR>
<% if @kitty.pictures.any? %>
<h5>Pictures of <%= @kitty.name %></h5>
  <div id="mycarousel" class="jcarousel-skin-tango">
    <ul>
      <!-- The content will be dynamically loaded in here -->
    </ul>
  </div>
        </table>
<% else %>
<h3>This Kitty has no pictures yet!</h3>
<% end %>
<input type=hidden id=kittynumber value=<%= @kitty.id %>>
<% if @kitty.user == current_user %>
<%= link_to "Add pictures!", '/pictures/new?kitty_id=' + @kitty.id.to_s %>
<% end %>

app/views/layouts/_header.html.erb
<header>
<table><tr><td>

  <%= link_to logo, root_path %>

</td><td>
<nav class="round">
<ul>
<li><%= link_to "Home", root_path %></li>
<% if signed_in? %>
<li><%= link_to "Users", users_path %></li>
<li><%= link_to "Profile", current_user %></li>
<li><%= link_to "Settings", edit_user_path(current_user) %></li>

<% end %>

<li><%= link_to "About", '/about' %></li>
<% if signed_in? %>
<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
<% else %>
<li><%= link_to "Sign in", signin_path %></li>
<% end %>

</ul>
</nav>
</td></tr></table>


</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
</head>
<body>
    <div class="container">
<%= render 'layouts/header' %>
<section class="round">
<% flash.each do |key, value| %>
<div class="flash <%= key %>"><%= value %></div>
<% end %>
<%= yield %>
</section>

      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/pages/about.html.erb
  <h1>Welcome to Kittybase!</h1>

  <p>
    Fill in your about stuff here!
  </p>

app/views/pages/home.html.erb
  <h1>Welcome to Kittybase!</h1>

  <p>
    This is the home page for Kittybase.
  </p>

app/views/pictures/_picture.html.erb
<li><%= link_to image_tag(picture.avatar.url(:thumb)), '/pictures/' + picture.id.to_s %></li>|

app/views/pictures/destroy.html.erb
<h1>Pictures#destroy</h1>
<p>Find me in app/views/pictures/destroy.html.erb</p>

app/views/pictures/new.html.erb
<%= form_for(@picture, :html => { :multipart => true }) do |f| %>
  <div class="field">
Enter a caption for your kitty!<BR>
        <%= f.text_field :caption %>
  </div>
  <div class="field">
Browse to where the file is:<BR>
        <%= f.file_field :avatar %>
  </div>
<%= f.hidden_field :kitty_id, { :value => params[:kitty_id] } %>
  <div class="actions">
    <%= f.submit "Upload!" %>
  </div>
<% end %>

app/views/pictures/show.html.erb
<font class="featured">Pictures of <%= @picture.kitty.name %></font>
<br><br>
<TABLE><TR>
<TD>
<%= image_tag @picture.avatar.url(:medium) %>
</TD>
</TR></TABLE>
<BR>
<h5><%= @picture.caption %></h5>
<% if @picture.kitty.user == current_user %>
<% if @picture.is_profile_pic == true %>
This is your profile picture!<BR>
<% else %>
<%= link_to "Make Profile Picture", make_profile_pic_picture_path %>
<% end %>
<% end %>
<BR>
<%= link_to "Back to Kitty", @picture.kitty %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(object.errors.count, "error") %>
prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
from being saved:</h2>
<p>There were problems with the following fields:</p>
<ul>
<% object.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/users/_user.html.erb
<li>
<%= gravatar_for user, :size => 30 %>
<%= link_to user.name, user %>
<% if current_user.admin? %>
| <%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
:title => "Delete #{user.name}" %>
<% end %>
</li>

app/views/users/edit.html.erb
<h1>Edit user</h1>
<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
<%= f.label :name %><br />
<%= f.text_field :name %>
</div>
<div class="field">
<%= f.label :email %><br />
<%= f.text_field :email %>
</div>
<div class="field">
<%= f.label :password %><br />
<%= f.password_field :password %>
</div>
<div class="field">
<%= f.label :password_confirmation, "Confirmation" %><br />
<%= f.password_field :password_confirmation %>
</div>
<div class="actions">
<%= f.submit "Update" %>
</div>
<% end %>
<div>
<%= gravatar_for @user %>
<a href="http://gravatar.com/emails">change</a>
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages' %>

<div class="field">
<%= f.label :name %><br />
<%= f.text_field :name %>
</div>
<div class="field">
<%= f.label :email %><br />
<%= f.text_field :email %>
</div>
<div class="field">
<%= f.label :password %><br />
<%= f.password_field :password %>
</div>
<div class="field">
<%= f.label :password_confirmation, "Confirmation" %><br />
<%= f.password_field :password_confirmation %>
</div>
<div class="actions">
<%= f.submit "Sign up" %>
</div>
<% end %>

</div>

app/views/users/show.html.erb
<h1>
<%= gravatar_for @user %>
<%= @user.name %>
</h1>

<% if @user.kitties.any? %>
  <h3>This user has <%= pluralize(@user.kitties.size,"kitty") %>!</h3>
       <table class="kitties" summary="Kitties that this user has"><tr>
          <%= render @kitties %>
        </tr></table>
<% else %>
<% if @user != current_user %>
<h3>This user has no kitties.  Tell them to add some!</h3>
<% else %>
<h3>Add some kitties!</h3>
<% end %>
      <% end %>

<%= link_to "Add a new Kitty", new_kitty_path if @user == current_user  %>